.\"
.\" Copyright (c) Kristaps Dzonsons <kristaps@bsd.lv>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt RSYNC 5
.Os
.Sh NAME
.Nm rsync
.Nd rsync wire protocol
.Sh DESCRIPTION
The
.Nm
protocol described in this relates to the BSD-licensed
.Xr openrsync 1 ,
a re-implementation of the GPL-licensed reference utility
.Xr rsync 1 .
It is compatible with version 27 of the reference.
.Pp
In this document, the
.Qq client process
refers to the utility as run on the operator's local computer.
The
.Qq server process
is run either on the local or remote computer, depending upon the
command-line given file locations.
.Pp
There are a number of options in the protocol that are dictated by
command-line flags.
These are shared by both
.Xr openrsync 1
and
.Xr rsync 1 .
.Ss Data types
The binary protocol encodes all data in little-endian format.
Integers are signed 32-bit, shorts are signed 16-bit, bytes are unsigned
8-bit.
A long is variable-length.
For values less than the maximum integer, the value is transmitted and
read as a 32-bit integer.
For values greater, the value is transmitted first as a maximum integer,
then a 64-bit signed integer.
.Pp
There are three types of checksums: long (slow), short (fast), and
whole-file.
The fast checksum is a derivative of Adler-32.
The slow checksum is MD4,
made over the checksum seed first (serialised in little-endian format),
then the data.
The whole-file applies MD4 to the file first, then the checksum seed at
the end (also serialised in little-endian format).
.Ss Multiplexing
Most
.Nm
transmissions are wrapped in a multiplexing envelope protocol.
It is composed as follows:
.Pp
.Bl -enum -compact
.It
envelope header (4 bytes)
.It
envelope payload (arbitrary length)
.El
.Pp
The first byte of the envelope header consists of a tag.
If the tag is 7, the payload is normal data.
Otherwise, the payload is out-of-band server messages.
If the tag is 1, it is an error on the sender's part and must trigger an
exit.
This limits message payloads to 24 bit integer size,
.Li 0x00ffffff .
.Pp
The only data not using this envelope are the initial handshake between
client and server.
.Ss File list
A central part of the protocol is the file list, which is generated by
the sender.
It consists of all files that must be sent to the receiver, either
explicitly as given or recursively generated.
.Pp
The file list itself consists of filenames and attributes (mode, time,
size, etc.).
Filenames must be relative to the destination root and not be absolute
or contain backtracking.
So if a file is given to the sender as
.Pa ../../foo/bar ,
it must be sent as
.Pa foo/bar .
.Pp
The file list should be cleaned of inappropriate files prior to sending.
For example, if
.Fl l
is not specified, symbolic links may be omitted.
Directory entries without
.Fl r
may also be omitted.
Duplicates may be omitted.
.Pp
The receiver
.Em must not
assume that the file list is clean.
It should not omit inappropriate files from the file list (which would
affect the indexing), but may omit them during processing.
.Pp
Prior to be sent from sender to receiver, and upon being received, the
file list must be lexicographically sorted such as with
.Xr strcmp 3 .
Subsequent references to the file are by index in the sorted list.
.Ss Asynchrony
The sender and receiver need not work in lockstep.
The receiver may send file update requests as quickly as it parses them,
and respond to the sender's update notices on demand.
Similarly, the sender may read as many update requests as it can, and
service them in any order it wishes.
.Pp
The sender and receiver synchronise state only at the end of phase.
.Pp
The reference
.Xr rsync 1
takes advantage of this with a two-process receiver, one for sending
update requests (the generator) and another for receiving.
.Xr openrsync 1
uses an event-loop model instead.
.Sh PROTOCOL
The client can operate in sender or receiver mode depending upon the
command-line source and destination.
.Pp
If the destination directory (sink) is remote, the client is in sender
mode: the client will push its data to the server.
If the source file is remote, it is in receiver mode: the server pushes
to the client.
If neither are remote, the client operates in sender mode.
These are all mutually exclusive.
.Ss Handshake
When the client starts, regardless its mode, it first handshakes the
server.
This exchange is
.Em not
multiplexed.
The server performs the same operation, but writing instead of reading.
.Pp
.Bl -enum -compact
.It
write local version (integer)
.It
read remote version (integer)
.It
read random seed (integer)
.El
.Pp
Following this, the client multiplexes when reading from the server.
Transmissions sent from client to server are not multiplexed.
It then enters the
.Sx File exchange
protocol.
.Ss File exchange
The receiver starts by reading the rule filter list if in server mode
and
.Fl -del
is specified.
If not in server mode, it writes the list.
The sender performs the same actions, except reversed.
.Pp
.Bl -enum -compact
.It
rule length or zero to stop reading rules (integer)
.Bq Em flist-rule-len
.It
rule string (variable of rule length)
.Bq Em flist-rule
.El
.Pp
The receiver then reads the
.Sx File list
as follows.
The sender performs the same actions, except writing.
Prior to being sent, the sender must lexicographically sort the list.
.Pp
.Bl -enum -compact
.It
read status byte (byte)
.Bq Em flist-status
.Bl -dash -compact
.It
this bit-field may consist of the following:
.Bl -tag -compact -width Ds
.It 0x01
A top-level directory.
(Only applies to directory files.)
If specified, the matching local directory is for deletions.
.It 0x02
Do not send the file mode: it is a repeat of the last file's mode.
.It 0x08
Like
.Li 0x02 ,
but for the user id.
.It 0x10
Like
.Li 0x02 ,
but for the group id.
.It 0x20
Inherit some of the prior file name.
Enables the inherited filename length transmission.
.It 0x40
Use full integer length for file name.
Otherwise, use only the byte length.
.It 0x80
Do not send the file modification time: it is a repeat of the last
file's.
.El
.El
.It
if status has
.Li 0x20 ,
read inherited path length (byte)
.Bq Em flist-name-offset
.It
if status has
.Li 0x40 ,
read long path length (integer)
.Bq Em flist-name-len-long
.It
otherwise, if status doesn't have
.Li 0x40 ,
read short path length (byte)
.Bq Em flist-name-len-short
.It
read path (variable: long or short length)
.Bq Em flist-name
.It
file length (long)
.Bq Em flist-length
.It
if status doesn't have
.Li 0x80 ,
read file modification time (time_t/integer)
.Bq Em flist-mtime
.It
if status doesn't have
.Li 0x2 ,
read file mode (mode_t/integer)
.Bq Em flist-mode
.It
if
.Fl o
and status doesn't have
.Li 0x8 ,
read the user id (integer)
.Bq Em flist-uid
.It
if
.Fl g
and status doesn't have
.Li 0x10 ,
read the group id (integer)
.Bq Em flist-gid
.It
if a special file,
.Fl D ,
and status doesn't have
.Li 0x4 ,
read the device
.Dq rdev
type (integer)
.Bq Em flist-rdev
.It
if a symbolic link and
.Fl l ,
read the link target's length (integer)
.Bq Em flist-link-len
.It
if a symbolic link and
.Fl l ,
read the link target (variable of link target length)
.Bq Em flist-link
.It
if
.Fl H ,
read the device (long)
.Pq before protocol 26, this is an int
.Bq Em flist-dev
.It
if
.Fl H ,
read the inode (long)
.Pq before protocol 26, this is an int
.Bq Em flist-inode
.It
if
.Fl c ,
read the MD4 checksum (16 B)
.Bq Em flist-checksum
.El
.Pp
If
.Fl o
and not
.Fl -numeric-ids
has been specified, read the identifier map.
.Pp
.Bl -enum -compact
.It
read identifier or zero to indicate end of set (integer)
.Bq Em flist-uidgid-id
.It
read non-zero length of user name (byte)
.Bq Em flist-uidgid-len
.It
read user name (prior length)
.Bq Em flist-uidgid-name
.El
.Pp
Repeat that sequence for groups if
.Fl g
and not
.Fl -numeric-ids
has been specified.
.Pp
The sender then sends any IO error values, which for
.Xr openrsync 1
is always zero.
The receiver reads it.
.Pp
.Bl -enum -compact
.It
constant zero (integer)
.Bq Em io-error-value
.El
.Ss Update exchange
Following that, the sender receives data regarding the receiver's copy
of the file list contents.
This data is not ordered in any way.
The receiver performs the same actions, except writing.
Each of these requests starts as follows:
.Pp
.Bl -enum -compact
.It
read file index (integer)
.Bq Em file-cont-index
.Bl -dash -compact
.It
If <0, increment phase and re-run.
The phase starts in phase 1, then proceeds to phase 2, and phase 3
signals an end of transmission (no subsequent blocks).
If a phase change occurs, the sender must write back the -1 constant
integer value and increment its own phase.
.El
.It
read block index (integer)
.Bq Em block-cont-index
.Bl -dash -compact
.It
In
.Pq Fl n
mode, the sender may immediately write back the index (integer) to skip
the following.
.El
.It
read number of blocks (integer)
.Bq Em block-cont-count
.It
read block length in the file (integer)
.Bq Em block-cont-length
.It
read long checksum length (integer)
.Bq Em block-cont-cs-length
.It
read terminal (remainder) block length (integer)
.Bq Em block-cont-rem
.It
then processing for each block:
.Bl -enum -compact
.It
read short checksum (integer)
.Bq Em block-cont-block-cs-short
.It
read long checksum (bytes of checksum length)
.Bq Em block-cont-block-cs-long
.El
.El
.Pp
The receiver then compares the two files, block by block, and updates
the server with mismatches as follows.
The sender performs the same actions, except writing.
.Pp
.Bl -enum -compact
.It
read file index (integer)
.Bq Em file-index
.Bl -dash -compact
.It
if <0, halt and change phase
.El
.It
read number of blocks (integer)
.Bq Em file-block-count
.It
block length (integer)
.Bq Em file-block-length
.It
long checksum length (integer)
.Bq Em file-block-cs-length
.It
remainder block length (integer)
.Bq Em file-block-rem
.It
then processing for each block:
.Bl -dash -compact
.It
for each block in uncompressed exchange
.Bl -enum -compact
.It
read header value (integer)
.Bq Em block-xchng-unc-1
.Bl -dash -compact
.It
if value is 0, no more blocks, halt
.It
if value >0, remote chunk size
.Bl -enum -compact
.It
read data chunk of the given size
(variable bytes)
.Bq Em block-xchng-unc-1a
.It
return to
.Bq block-xchng-unc-1
.El
.It
if value <0, recast to an index as (-value - 1)
.Bl -enum -compact
.It
copy from local file
.It
return to
.Bq block-xchng-unc-1
.El
.El
.It
read whole-file long checksum (16 bytes)
.Bq Em block-xchng-com-2
.El
.It
or for each block in compressed exchange (zlib)
.Bl -enum -compact
.It
read header flags (byte)
.Bq Em block-xchng-com-1
.Bl -dash -compact
.It
if value is 0, no more blocks, halt
.It
if bit 0x40 is set and bit 0x80 is not set, stay at the current block
index
.Bl -enum -compact
.It
read size low bits, then set chunk size as bit-wise OR with flag value
shifted left and without its 0x40 set (byte)
.Bq Em block-xchng-com-1a
.It
read data chunk of produced size (variable bytes) 
.Bq Em block-xchng-com-1b
.It
return to
.Bq block-xchng-com-1
.El
.It
if bit 0x80 is set, set next block index as lower six bits and whether
to read a
.Dq run size
if bit 0x40 is set
.It
if bit 0x20 is set and not bit 0x80, set whether to read a
.Dq run size
if bit 0x01 is set
.Bl -enum -compact
.It
read next block index (integer)
.Bq Em block-xchng-com-1c
.El
.It
if reading a run size
.Bl -enum -compact
.It
read lower byte of two-byte data size (byte)
.Bq Em block-xchng-com-1d
.It
read upper byte of two-byte data size (byte)
.Bq Em block-xchng-com-1e
.El
.It
if a run size has been read and is non-zero, decompress that number of
sequential blocks, then return to
.Bq block-xchng-com-1
.El
.It
read whole-file long checksum (16 bytes)
.Bq Em block-xchng-unc-2
.El
.El
.El
.Pp
The sender then either handles the next queued file or, if the receiver
has written a phase change, the phase change step.
.Pp
If the sender is the server and
.Fl v
has been specified, the sender must send statistics.
.Pp
.Bl -enum -compact
.It
total bytes read (long)
.It
total bytes written (long)
.It
total size of files (long)
.El
.Pp
Finally, the sender must read a final constant-value integer.
.Pp
.Bl -enum -compact
.It
end-of-sequence -1 value (integer)
.El
.Pp
If in receiver mode, the inverse above (write instead of read, read
instead of write) is performed.
.Pp
The receiver begins by conditionally writing, then reading, the
exclusion list count, which is always zero.
.Pp
.Bl -enum -compact
.It
if client, send zero (integer)
.It
if receiver and
.Fl -delete ,
read zero (integer)
.El
.Pp
The receiver then proceeds with reading the
.Sx File list
as already
defined.
Following the list, the receiver reads the IO error, which must be zero.
.Pp
.Bl -enum -compact
.It
constant zero (integer)
.El
.Pp
The receiver must then sort the file names lexicographically.
.Pp
If there are no files in the file list at this time, the receiver must
exit prior to sending per-file data.
It then proceeds with the file blocks.
.Pp
For file blocks, the receiver must look at each file that is not up to
date, defined by having the same file size and timestamp, and send it to
the server.
Symbolic links and directory entries are never sent to the server.
.Pp
After the second phase has completed and prior to writing the
end-of-data signal, the client receiver reads statistics.
This is only performed with
.Pq Fl v .
.Pp
.Bl -enum -compact
.It
total bytes read (long)
.It
total bytes written (long)
.It
total size of files (long)
.El
.Pp
Finally, the receiver must send the constant end-of-sequence marker.
.Pp
.Bl -enum -compact
.It
end-of-sequence -1 value (integer)
.El
.\" .Sh CONTEXT
.\" For section 9 functions only.
.\" .Sh RETURN VALUES
.\" For sections 2, 3, and 9 function return values only.
.\" .Sh ENVIRONMENT
.\" For sections 1, 6, 7, and 8 only.
.\" .Sh FILES
.\" .Sh EXIT STATUS
.\" For sections 1, 6, and 8 only.
.\" .Sh EXAMPLES
.\" .Sh DIAGNOSTICS
.\" For sections 1, 4, 6, 7, 8, and 9 printf/stderr messages only.
.\" .Sh ERRORS
.\" For sections 2, 3, 4, and 9 errno settings only.
.Sh SEE ALSO
.Xr openrsync 1 ,
.Xr rsync 1 ,
.Xr rsyncd 5
.\" .Sh STANDARDS
.\" .Sh HISTORY
.\" .Sh AUTHORS
.\" .Sh CAVEATS
.Sh BUGS
Time values are sent as 32-bit integers.
.Pp
When in server mode
.Em and
when communicating to a client with a newer protocol (>27), the phase
change integer (-1) acknowledgement must be sent twice by the sender.
The is probably a bug in the reference implementation.
